README: Update scapy version
When using scapy 2.4.3 on newer Python version, there will be an error
with loading the scapy module:

        from scapy.modules.six.moves import range
    ModuleNotFoundError: No module named 'scapy.modules.six.moves'

This is solved by upgrading to a newer Scapy version.